### ISSUE TITLE
Unable to Launch Synplay on Mint 22.1

### ISSUE THREAD

**Issue by githubplanetarparrot** [Syncplay/syncplay#723]
**Describe the bug**
Syncplay is failing to launch when installed on Mint 22.1. 

**To Reproduce**
1. Install Syncplay from Mint Software Manager
2. Click on Launch

**Expected behavior**
Syncplay to launch a gui.

This is what occurs when running Syncplay from CLI.
` ~syncplay

Traceback (most recent call last):
  File "/usr/bin/syncplay", line 33, in <module>
    sys.exit(load_entry_point('syncplay==1.7.0', 'gui_scripts', 'syncplay')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/bin/syncplay", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/syncplay/ep_client.py", line 3, in <module>
    from syncplay.clientManager import SyncplayClientManager
  File "/usr/lib/python3/dist-packages/syncplay/clientManager.py", line 4, in <module>
    from syncplay.ui.ConfigurationGetter import ConfigurationGetter
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/syncplay/ui/ConfigurationGetter.py", line 8, in <module>
    from configparser import SafeConfigParser, DEFAULTSECT
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/usr/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'? 
`

**Version and platform:**
 - OS: [e.g. Windows 10 64-bit or macOS 10.15]
 - Syncplay version and build type: [e.g. Syncplay 1.6.9 portable]
 - Media player and version:  [e.g. VLC 3.0.16 32-bit]

**Additional context**
My python information is below:
` Python 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] on linux`

System Information
[https://termbin.com/2qom](https://termbin.com/2qom)

**Comment by Et0h** [comment]
Hi, I'm not the Linux guy (that'd be @daniel-123) but the reference to Syncplay 1.7.0 (when Syncplay is on 1.7.4) makes me think you are installing the software from an unmaintained package.

As such, either you should contact whoever maintains the relevant Linux Mint package to fix the issue or you should follow the instructions at https://syncplay.pl/syncplay-1-7-4/ and https://syncplay.pl/guide/install/ on how to install Syncplay 1.7.4.

I believe the issue with Syncplay 1.7.0 is that it is not compatible with Pyron 3.12 as per https://github.com/Syncplay/syncplay/issues/633 which I think was fixed in Syncplay 1.7.1

**Comment by daniel-123** [comment]
The problem you have has been fixed in 7456a94, which is included in Syncplay releases 1.7.1 and newer. Before that Syncplay can only work with Python 3.11

It seems that this is inevitably going to be a problem with Ubuntu 24.04 LTS as well as all of its derivatives: it has the same combination of Syncplay 1.7.0 and Python 3.12.

The simplest solution I see is to uninstall the Syncplay package you have from repositories and install newer version from our [releases page](https://github.com/Syncplay/syncplay/releases).

**Comment by githubplanetarparrot** [comment]
Thank you or the information. I had a feeling based on some of the issues I was having may have been a version issue. I will confirm the package from the github works once I have a moment. Once I confirm it works I will contact the package manager and close this issue.
